# Generated by Django 4.1.7 on 2023-03-19 21:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='file',
            old_name='orignal_file_name',
            new_name='original_file_name',
        ),
    ]
